# Generated by Django 5.2.7 on 2025-11-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="subject",
            field=models.CharField(
                default="Без темы", max_length=200, verbose_name="Тема комментария"
            ),
            preserve_default=False,
        ),
    ]
