# Generated by Django 5.2.7 on 2025-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Одобрен"),
        ),
    ]
